services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "5050:8501"
    environment:
      PORT: "8501"
      WHISPER_MODEL: ${WHISPER_MODEL:-tiny.en}
    volumes:
      - ./uploads:/app/uploads
      - ./transcripts:/app/transcripts
      - ./outputs:/app/outputs
    restart: unless-stopped
